### ISSUE TITLE
Break total latency into latency / components in the stack for the Trade measurement

### ISSUE THREAD

**Issue by mrdavidlaing** [fandrei/AppMetrics#102]
We have access to the following data
1.  The full C# stack CIAPI request latency measurement
2.  The default page latency measurement, which measures time for IIS's default page
3.  The server side IIS logs, which measure latency of internal systems to respond

We need to generate a report showing what portions of the full Trade latency can be attributed to each piece.

This will guide where the first optimisations should be done.

**Comment by mrdavidlaing** [comment]
There are two further API "test" services that we could consider measuring: (see https://ciapipreprod.cityindextest9.co.uk/tradingapi)
1. /smoketest -> This returns a serialized DTO from the ASP.NET/WebAPI layer, without any interaction with any backend services
2. /smoketest/authenticated -> Same as /smoketest buy includes a session authentication check (single call to backend Authentication service)

**Comment by fandrei** [comment]
http://labs.cityindex.com/performance/2013/01/30/ciapi-production-latency-monitoring-appmetrics-vs-iis-august-2012-to-january-2013/
