### ISSUE TITLE
Changing the CIAPILatencyCollector config url via the command line doesn't seem to work

### ISSUE THREAD

**Issue by mrdavidlaing** [fandrei/AppMetrics#108]
Step ["Install the CIAPILatencyMonitor service > 3"](https://github.com/fandrei/CiapiLatencyCollector/wiki/Installation-instructions)

```
 "C:\ProgramData\City Index\CIAPI Latency Collector\bin\CiapiLatencyCollectorConfig.exe" -username:{config_username} -password:{config_password} -nodename:{name_of_node} -configserver=http://config.metrics.{your_tld}
```

Seems to fail to actually change the value within C:\Program Data\City Index\CIAPILatencyCollector\AppConfig.xml

So, if you entered the invalid config url during the install process; correcting it from the command line doesn't seem to work.

This could be a permissions error, and the fix would be to amend the documentation to clearly state which user needs to run that command.

**Comment by fandrei** [comment]
You need to use -configserver: instead (with trailing colon)

**Comment by mrdavidlaing** [comment]
DOH!  

Have fixed the documentation.

At least it was an easy fix :)
