### ISSUE TITLE
Howto set env variables AppMetricsTest_ServiceRootFolder?

### ISSUE THREAD

**Issue by mrdavidlaing** [fandrei/AppMetrics#120]
The build on the internal City Index TFS build farm is failing in [ContinuousIntegration/testAndCover.xml](https://github.com/fandrei/AppMetrics/blob/master/ContinuousIntegration/testAndCover.xml#L44-46)

```
<SetEnvVariable Name="AppMetricsTest_ServiceRootFolder" Value="$(AppMetricsTest_ServiceRootFolder)"/>
<SetEnvVariable Name="AppMetricsTest_DataFolder" Value="$(AppMetricsTest_DataFolder)"/>
<SetEnvVariable Name="AppMetricsTest_AccessKey" Value="$(AppMetricsTest_AccessKey)"/>
```

with error:

```
D:\Dev\Builds\6\CIAPI latency monitoring\AppMetrics\Sources\src\AppMetrics\ContinuousIntegration\testAndCover.xml (44): The "SetEnvVariable" task was not given a value for the required parameter "Value".
```

I see that on the EC2 TFS2010 build server there are a set of environment variables set with these names.

Is there a way remove the dependancy on having these environment variables set on the build agent.  

My specific problem is that CI TFS runs a cluster of 6 build agents, which the job running on whichever one is free.  I'd prefer not to have to manually add this env setting to every (existing) TFS build agent (and every new one that gets added).

Is this possible?

Can we calculate these env variables from an existing variable like: `$(MSBuildProjectDirectory)`

**Comment by fandrei** [comment]
If we assume that these values are fixed to some relative paths and we don't need to call external server, I can set them default values.

**Comment by mrdavidlaing** [comment]
Managed to set the pathers from `$(BinariesRoot)` -> 42edc2b5318ce7afac214e0e0686f08dad936bfa

Can we hardcode `AppMetricsTest_AccessKey`?  or perhaps set it at in the TFS build definition screen?

**Comment by fandrei** [comment]
Fixed. AccessKey can be assigned any value in this case, because by default it's not required on the server side.
