### ISSUE TITLE
config.aspx / "Check data being received" link hardcoded to metrics.labs.cityindex.com

### ISSUE THREAD

**Issue by mrdavidlaing** [fandrei/AppMetrics#124]
Specifically, on `http://config.metrics.cityindex.com/config.aspx`

the link points to `http://analytics.metrics.labs.cityindex.com` when it should point to `http://analytics.metrics.cityindex.com`

This needs to be a config setting so it can be changed during deployment.

**Comment by fandrei** [comment]
As a part of refactoring - maybe it's better to make all 3 sites sub-parts of a single metrics site?

**Comment by fandrei** [comment]
As a temporary solution - try to infer analytics URL from config site URL.

**Comment by mrdavidlaing** [comment]
Just make it a config option.

I think trying to combine the 3 separate sites is going to have quite a large effect w.r.t the documentation, build process and retraining the delivery team for the live environment.  

Lets hold off on this refactoring for the meanwhile.  I'm currently considering whether we should move the whole project over to a cloudfoundry powered environment so as to remove the server management aspect of running the service.  If we do that, then we'll have to do some significant architectural refactoring.  That would be the right time to make this kind of change.

**Comment by fandrei** [comment]
Added option "CheckDataUrl" (see here https://github.com/fandrei/CiapiLatencyCollector/wiki/Installation-instructions)
