### ISSUE TITLE
Update of config.metrics.cityindex.com failed to add <PageUrl> element to AppSettings.xml

### ISSUE THREAD

**Issue by mrdavidlaing** [fandrei/AppMetrics#126]
The update of production server failed to add `<PageUrl>` element to `D:\Websites\config.metrics.cityindex.com\CIAPILatencyCollectorConfig\AppSettings`

The config remained as 

```
<MonitorSettings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <LogEventUrl>http://metrics.cityindex.com/LogEvent.ashx</LogEventUrl>
  <ApplicationKey>CiapiLatencyCollector</ApplicationKey>
  <Monitors>
    <LatencyMonitor xsi:type="DefaultPageMonitor">
      <PeriodSeconds>6</PeriodSeconds>
    </LatencyMonitor>
  </Monitors>
</MonitorSettings>
```

Where as it should have been changed (automatically or manually) to 

```
<MonitorSettings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <LogEventUrl>http://metrics.cityindex.com/LogEvent.ashx</LogEventUrl>
  <ApplicationKey>CiapiLatencyCollector</ApplicationKey>
  <Monitors>
    <LatencyMonitor xsi:type="DefaultPageMonitor">
      <PeriodSeconds>6</PeriodSeconds>
      <PageUrl>https://ciapi.cityindex.com/TradingAPI/Scripts/tradingApi.js</PageUrl>
    </LatencyMonitor>
  </Monitors>
</MonitorSettings>
```

This has been manually rectified, but there are some underlying issues that need to be addressed:

(a) We forgot this from [the deployment notes ](https://github.com/fandrei/AppMetrics/wiki/Manual-upgrade-steps)
(b) There were [no exceptions thrown](http://analytics.metrics.cityindex.com/GetReport.ashx?Application=CiapiLatencyCollector&Period=1.10%3A0%3A0&Type=Exceptions&SliceByLocation=Countries&SliceByFunction=No&SliceByNodeName=No&Locations=&FunctionFilter=)

**Comment by fandrei** [comment]
Added deployment note. Added exceptions for non-set URLs.
Config:
config.metrics.labs.cityindex.com\App_Data\web.config

```
     <add key="CheckDataUrl" value="http://analytics.metrics.labs.cityindex.com"/>
```
