### ISSUE TITLE
Fix service config UI being shown for Windows Installer passive installations and repairs.

### ISSUE THREAD

**Issue by sopel** [fandrei/AppMetrics#134]
I'm having problems with the silent installation done via CloudFormation in the context of #132 - while I'm not at all positive that this is related, I've noticed the following issue:
- installing from a CLI via `AppMetrics.AgentService.msi /quiet` works fine
- installing from a CLI via `AppMetrics.AgentService.msi /passive` does show the service config UI, which is violating the specification of `/passive`
  - likewise the service config UI is shown for a repair action, which should run without prompts too (doesn't matter here, just for completeness)

This stems from an incomplete check within the custom action [RunConfig](https://github.com/fandrei/AppMetrics/blob/fecd85212a125b1f8d4ce025e2f97ca0d5d680e2/AgentService.Setup/Product.wxs#L83):

``` xml
<Custom Action='RunConfig' After='InstallFiles'>
    <!-- product is installing and UILevel is not INSTALLUILEVEL_NONE -->
    $ProductComponent = 3 AND NOT UILevel = 2
</Custom>
```

The comparison must at least be extended to cover `msiUILevelBasic` too (see [Installer.UILevel property](http://msdn.microsoft.com/en-us/library/windows/desktop/aa369487%28v=vs.85%29.aspx) - also these are bitwise flags, so I think it requires usage of [Bitwise Numeric Operators](http://msdn.microsoft.com/en-us/library/windows/desktop/aa368012%28v=vs.85%29.aspx) to be on the safe side.
- The latter is the one thing that might in fact cause the issue I'm seeing eventually, namely if CloudFormation is performing the silent installation of the MSI with an UILevel other than 2 by adding one of those flags, it would trigger a modal UI during a headless operation and fail accordingly.
- Given the available bitwise operators and the explanation in [Determining UI Level from a Custom Action](http://msdn.microsoft.com/en-us/library/windows/desktop/aa368281%28v=vs.85%29.aspx) it might be more reasonable to invert the condition and only execute the custom action when `msiUILevelFull` or `msiUILevelReduced` are selected.

**Comment by fandrei** [comment]
Wow. I wish all bug reports were like this.

**Comment by fandrei** [comment]
Done as suggested - i.e. show config dialog only in msiUILevelFull and msiUILevelReduced modes. Works well for you?

**Comment by mrdavidlaing** [comment]
:+1: for awesome bug reports.  @sopel - I'm sensing a tech radar article on
this...

On Wednesday, February 6, 2013, Andrei Faber wrote:

> Done as suggested - i.e. show config dialog only in msiUILevelFull and
> msiUILevelReduced modes. Works well for you?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/fandrei/AppMetrics/issues/134#issuecomment-13166176.

## 

David Laing
Open source @ City Index - github.com/cityindex
http://davidlaing.com
Twitter: @davidlaing

**Comment by sopel** [comment]
Excellent, this works as desired in itself now and has indeed solved the issue I've encountered as well, thanks :)
