### ISSUE TITLE
Browser (silverlight?) application to measure client latency

### ISSUE THREAD

**Issue by mrdavidlaing** [fandrei/AppMetrics#15]
This is a browser based application (silverlight?).  It should:

Create a session
Get a market list for 20 markets
Get 250 minutes of price history data for each market
Subscribe to prices for each market

We need to log "performance" related metrics back to AppMetrics so we can get a measurement of what the performance is like from the application perspective.
- Latency between making a request and receiving the data

We will use this application to measure the performance from machines in the UK & China; and compare different API proxy acceleration solutions.

(in the future we will want to measure price latency, but this is going to be tricky until we figure out how to syncronise the client & server clocks)

**Comment by mrdavidlaing** [comment]
http://cityindex.api.mashery.com has been set up as a proxy for https://ciapi.cityindex.com

This requires an api_key, and applies throttles based on that key.  The proxy is hosted on the mashery cloud, so we want to measure if how this affects latency for remote customers.

Sample calls:

```
http://cityindex.api.mashery.com/TradingApi/market/71442/barhistory?api_key=2mn8skr4uhgeafktwqewvw64&interval=MINUTE&span=1&pricebars=15&UserName=XX554424&Session=f1650c41-594e-40c7-87ce-537356b7d3d3

->

https://ciapi.cityindex.com/TradingApi/market/71442/barhistory?interval=MINUTE&span=1&pricebars=15&UserName=XX554424&Session=f1650c41-594e-40c7-87ce-537356b7d3d3
```

**Comment by mrdavidlaing** [comment]
Until CIAPI.CS silverlight is fixed, start by measuring latency in Excel Addin

Initially, just connect directly to ciapi.cityindex.com

**Comment by fandrei** [comment]
I've added metrics of server calls latency to the Excel add-in (at this moment it collects duration of every call to the server, in seconds). Available in the bleeding edge build.
