### ISSUE TITLE
Excel Addin Latency report

### ISSUE THREAD

**Issue by mrdavidlaing** [fandrei/AppMetrics#16]
Showing latency of each request type
grouped by location / machine type
showing data as histograms

**Comment by fandrei** [comment]
I've put my sample here: https://github.com/fandrei/AppMetrics/blob/master/Samples/CIAPI.CS.Excel%20-%20Latency%20report%202.xlsx

It provides box-and-whisker plot and latency histogram, but no grouping by location yet.
PowerPivot has memory problems when importing much data (it bumps into max 32bit process memory limitation - 2GB). Maybe we can optimize this report.

**Comment by fandrei** [comment]
New updated version of the report including new logs data, slicing by regions and additional small improvements.
(I had to truncate some sessions, because Excel wasn't capable to handle all data)

**Comment by fandrei** [comment]
new version of report, based on pre-calculated data: https://github.com/fandrei/AppMetrics/blob/master/Samples/CIAPI.CS.Excel%20-%20Latency%20report%203.xlsx
