### ISSUE TITLE
Excel shows error messages and hangs when trying to retrieve big amout of data

### ISSUE THREAD

**Issue by fandrei** [fandrei/AppMetrics#18]
Using this URL http://184.73.228.71/AppMetrics/DataService.svc/Records?appKey=CIAPI.CS.Excel&period=7.0:0:0
This request includes one session with huge amount of events (~200'000), and it seems Excel data feed import facilities have problems with such amount of data. It's necessary to find a workaround.

**Comment by mrdavidlaing** [comment]
Bummer.

I wonder if a custom Excel addin could get around:

(1) Max record limits
(2) Incremental updates

?

On 26 December 2011 07:07, fandrei <
reply@reply.github.com

> wrote:
> 
> Using this URL
> http://184.73.228.71/AppMetrics/DataService.svc/Records?appKey=CIAPI.CS.Excel&period=7.0:0:0
> This request includes one session with huge amount of events (~200'000),
> and it seems Excel data feed import facilities have problems with such
> amount of data. It's necessary to find a workaround.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/fandrei/AppMetrics/issues/18

## 

David Laing
Open source @ City Index - github.com/cityindex
http://davidlaing.com
Twitter: @davidlaing

**Comment by fandrei** [comment]
1) impossible to workaround (limited by Excel internally)

http://msdn.microsoft.com/en-us/library/ff700514.aspx#Office2007excelPerf_BigGridIncreasedLimitsExcel
http://newtech.about.com/od/microsoft/tp/5-Cool-Things-You-Can-Do-With-PowerPivot-For-Excel.htm

Excel can handle about 1 million rows max, PowerPivot can handle theoretically unlimited number of rows, but limited by size of resulting Excel file (2 GB max)

2) downloading data to the client incrementally is not a problem, and I think we can feed these data to PowerPivot as textual files

**Comment by mrdavidlaing** [comment]
I guess then we need to do some "summarizing" work on the server; so that
the data downloaded to excel doesn't exceed the 2GB max

On 27 December 2011 06:06, fandrei <
reply@reply.github.com

> wrote:
> 
> 1) impossible to workaround (limited by Excel internally)
> 
> http://msdn.microsoft.com/en-us/library/ff700514.aspx#Office2007excelPerf_BigGridIncreasedLimitsExcel
> 
> http://newtech.about.com/od/microsoft/tp/5-Cool-Things-You-Can-Do-With-PowerPivot-For-Excel.htm
> 
> Excel can handle about 1 million rows max, PowerPivot can handle
> theoretically unlimited number of rows, but limited by size of resulting
> Excel file (2 GB max)
> 
> 2) downloading data to the client incrementally is not a problem, and I
> think we can feed these data to PowerPivot as textual files
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/fandrei/AppMetrics/issues/18#issuecomment-3279446

## 

David Laing
Open source @ City Index - github.com/cityindex
http://davidlaing.com
Twitter: @davidlaing

**Comment by mrdavidlaing** [comment]
Or perhaps we should be exporting data from the server to a local datastore
on the Excel PC that has some summarising capabilities - perhaps a
SQLExpress db?

On 27 December 2011 13:43, David Laing david@davidlaing.com wrote:

> I guess then we need to do some "summarizing" work on the server; so that
> the data downloaded to excel doesn't exceed the 2GB max
> 
> On 27 December 2011 06:06, fandrei <
> reply@reply.github.com
> 
> > wrote:
> > 
> > 1) impossible to workaround (limited by Excel internally)
> > 
> > http://msdn.microsoft.com/en-us/library/ff700514.aspx#Office2007excelPerf_BigGridIncreasedLimitsExcel
> > 
> > http://newtech.about.com/od/microsoft/tp/5-Cool-Things-You-Can-Do-With-PowerPivot-For-Excel.htm
> > 
> > Excel can handle about 1 million rows max, PowerPivot can handle
> > theoretically unlimited number of rows, but limited by size of resulting
> > Excel file (2 GB max)
> > 
> > 2) downloading data to the client incrementally is not a problem, and I
> > think we can feed these data to PowerPivot as textual files
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/fandrei/AppMetrics/issues/18#issuecomment-3279446
> 
> ## 
> 
> David Laing
> Open source @ City Index - github.com/cityindex
> http://davidlaing.com
> Twitter: @davidlaing

## 

David Laing
Open source @ City Index - github.com/cityindex
http://davidlaing.com
Twitter: @davidlaing

**Comment by fandrei** [comment]
I think the simplest way is to write a tool to make aggregations that we need, before importing data into Excel.

**Comment by fandrei** [comment]
I've created a tool to pre-calculate data for Excel RPC latency report (at this moment, it's implemented as console application and located in DataConvertor folder). It should be able to handle up to ~10'000'000 latency values. 
If we need to process more data, it will be necessary to use more sophisticated algorithms
