### ISSUE TITLE
Integrate GeoIP

### ISSUE THREAD

**Issue by fandrei** [fandrei/AppMetrics#19]
It's necessary to provide capability to lookup client's geo location by IP address

**Comment by mrdavidlaing** [comment]
Here is a possible geoip library - http://www.maxmind.com/app/csharp

On 27 December 2011 12:12, fandrei <
reply@reply.github.com

> wrote:
> 
> It's necessary to provide capability to lookup client's geo location by IP
> address
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/fandrei/AppMetrics/issues/19

## 

David Laing
Open source @ City Index - github.com/cityindex
http://davidlaing.com
Twitter: @davidlaing

**Comment by fandrei** [comment]
done (IP lookup is performed when creating report)
