### ISSUE TITLE
Publish NuGet AppMetrics.Client package on each build

### ISSUE THREAD

**Issue by mrdavidlaing** [fandrei/AppMetrics#21]
See CIAPI.CS for example on how to do this.

Basically you need to register the NuGet API key on the build server, and then call nuget push at the end of the build if all tests pass.

See https://github.com/cityindex/CIAPI.CS/blob/master/tools/msbuild/DropsAndPackaging.targets.xml#L20

**Comment by fandrei** [comment]
How I can register this API key on the server?

**Comment by mrdavidlaing** [comment]
http://bit.ly/sCzZGV

On 3 January 2012 11:39, fandrei <
reply@reply.github.com

> wrote:
> 
> How I can register this API key on the server?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/fandrei/AppMetrics/issues/21#issuecomment-3338826

## 

David Laing
Open source @ City Index - github.com/cityindex
http://davidlaing.com
Twitter: @davidlaing

**Comment by fandrei** [comment]
It's clear, but how I can execute this command on this server? ;)

**Comment by fandrei** [comment]
Permanently storing API key didn't work for some reason, so I pass it to build task at every build (using MaskPassword add-in to prevent showing in job output).

**Comment by mrdavidlaing** [comment]
That is probably a better solution, since we can now build on any build
agent

On 4 January 2012 05:36, fandrei <
reply@reply.github.com

> wrote:
> 
> Permanently storing API key didn't work for some reason, so I pass it to
> build task at every build (using MaskPassword add-in to prevent showing in
> job output).
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/fandrei/AppMetrics/issues/21#issuecomment-3350914

## 

David Laing
Open source @ City Index - github.com/cityindex
http://davidlaing.com
Twitter: @davidlaing
