### ISSUE TITLE
Occasional lack of data for /GetReport.ashx?Application=CIAPI.CS.Excel&Locations=United%20Kingdom&Period=0:1:0

### ISSUE THREAD

**Issue by mrdavidlaing** [fandrei/AppMetrics#29]
http://analytics.metrics.labs.cityindex.com/GetReport.ashx?Application=CIAPI.CS.Excel&Locations=United%20Kingdom&Period=0:1:0

Produces:

```
Period: 00:01:00    Generated at: 2012-02-16 19:38:19   Generation time: 00:00:28.1731201
Country City    Location    FunctionName    Count   Average Min LowerQuartile   Median  UpperQuartile   Max
```

I have seen it succeed, but of course now I can't get an example of that.

Increasing the period seems to always work: - http://analytics.metrics.labs.cityindex.com/GetReport.ashx?Application=CIAPI.CS.Excel&Locations=United%20Kingdom&Period=1:0:0

I have been running the Excel Addin continuously from my London UK machine, so there should always be data flowing into the system.

**Comment by fandrei** [comment]
I can confirm this problem; there are periods when data is not transferred to the server for some unknown reason. This needs more investigation.

**Comment by mrdavidlaing** [comment]
Lets delay investigating this until we're collecting data using the specialist app rather than Excel.

The specialist collection app needs to log when it has been unable to send data.

**Comment by mrdavidlaing** [comment]
Cannot reproduce.  closing
