### ISSUE TITLE
Latency collector reference implementation

### ISSUE THREAD

**Issue by mrdavidlaing** [fandrei/AppMetrics#31]
Separate application that instruments a small subset of RPC calls at a 1 minute interval.
- Logon
- List markets
- Logout

Should be installed as a windows service.

Must be autoupdatable.

Needs to serve as a reference application for other latency data collector implementations to copy.

**Comment by fandrei** [comment]
What credentials it should use? Demo account will require periodic renewal.

**Comment by mrdavidlaing** [comment]
XX870869 / password.

This is a test account tied to the Latency Test account operator.

It shouldn't expire.

On 27 February 2012 05:46, fandrei <
reply@reply.github.com

> wrote:
> 
> What credentials it should use? Demo account will require periodic renewal.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/fandrei/AppMetrics/issues/31#issuecomment-4188371

## 

David Laing
Open source @ City Index - github.com/cityindex
http://davidlaing.com
Twitter: @davidlaing

**Comment by fandrei** [comment]
source code: https://github.com/fandrei/CiapiLatencyCollector
Jenkins build: http://ci.labs.cityindex.com:8080/job/CiapiLatencyCollector/
