### ISSUE TITLE
Report on the experience for the 98th percentile

### ISSUE THREAD

**Issue by mrdavidlaing** [fandrei/AppMetrics#32]
To better match existing internal reports, we need to report for the 98th percentile.

So, we need the average latency for the 98% percentile.

It would also be useful to know the number of measurements recorded below and above this averages

I'm looking to be able to create a report showing:

(a) What the average latency is for 98% of sessions
(b) How many sessions are worse than this?

**Comment by fandrei** [comment]
By which parameter select these 98% sessions? Per-session average value?
And how to calculate, if count of sessions is small (< 50)?

**Comment by mrdavidlaing** [comment]
Its the same way you select Upper / Lower quartile - which would also be
called 75 / 25 percentile.

On 19 March 2012 12:03, fandrei <
reply@reply.github.com

> wrote:
> 
> By which parameter select these 98% sessions? Per-session average value?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/fandrei/AppMetrics/issues/32#issuecomment-4571881

## 

David Laing
Open source @ City Index - github.com/cityindex
http://davidlaing.com
Twitter: @davidlaing

**Comment by fandrei** [comment]
It's not the same, because quartiles are calculated on single measurements level, rather than sessions. Just need to understand how these internal reports work to match them.

**Comment by fandrei** [comment]
I've made simple implementation working on the level of single measurements. View it using this:

http://analytics.metrics.labs.cityindex.com/GetReport.ashx?Application=CiapiLatencyCollector&Period=1.0:0:0&Type=AveragePercentile98

**Comment by mrdavidlaing** [comment]
Could you point me to the unit tests for this calculation so I make sure
I'm understanding exactly what it does.

On Tuesday, March 20, 2012, fandrei <
reply@reply.github.com>
wrote:

> I've made simple implementation working on the level of single
> measurements. View it using this:
> 
> http://analytics.metrics.labs.cityindex.com/GetReport.ashx?Application=CiapiLatencyCollector&Period=1.0:0:0&Type=AveragePercentile98
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/fandrei/AppMetrics/issues/32#issuecomment-4590965

## 

David Laing
Open source @ City Index - github.com/cityindex
http://davidlaing.com
Twitter: @davidlaing

**Comment by fandrei** [comment]
I hope this one can explain the idea
https://github.com/fandrei/AppMetrics/blob/e60398312f4545774de1dfb855f0aac86864eb21/Tests.Analytics/UnitTesting.cs#L68

**Comment by mrdavidlaing** [comment]
I think we have a miscommunication as to the meaning of percentile, and what I meant by the 98th percentile latency.  (I shouldn't have said average)

I've added some sample calculations done in R in commit 06e100ec19180623a0584f8897d0e2425e24dfe0 - which as you can see give different values.

I think we should switch to using [R.NET](http://rdotnet.codeplex.com/) for the analytics rather than waste time going through the debugging process on all the statistical measures.

**Comment by fandrei** [comment]
Well, to make things more complicated - there are different ways of calculating percentiles, giving different results.

Switching to R.NET certainly will remove need of debugging our statistical code, but it can add even more debugging of R.NET itself :)
(including deployment, initialization, etc)

**Comment by mrdavidlaing** [comment]
Let's

(a) Use R's definition of percentile, so we can check results against R
(b) Drop my silly request for "average of 98th percentile", we just want the boundary value below which 98% of values lie.
(c) Hold off on the use of R.NET for percentile calculation, but reconsider if we start doing more calculations.

**Comment by fandrei** [comment]
Ok. Maybe it's better to add it to the same report where we have quartiles and median?

**Comment by fandrei** [comment]
done... you can view it here:
http://analytics.metrics.labs.cityindex.com/GetReport.ashx?Application=CiapiLatencyCollector&Type=Percentile98

**Comment by mrdavidlaing** [comment]
Agreed - lets drop the Percentile98 report and just include the 98th percentile in the existing report along with the 75% percentile (upper quartile).  For completeness lets also add the 2nd percentile.

In all, the report would include:

Count, Average, Min, 2  25 (Lower quartile), 50 (median), 75 (upper quartile), 98, Max

With these we can get a feel for:
1.  The average
2.  The spread or variability
3.  A level of confidence in the numbers (from the count)

If we can also add an error count, that would help with (3)

"Good network latency" numbers are defined by (a) a low average (b) low spread (c) high confidence = high count + low error

**Comment by fandrei** [comment]
ok, I've added percentiles and exceptions count to the stat summary report. but you need to update Solarwinds script to retrieve data from right columns
now this report returns the following columns:
Country City    Location    FunctionName    Count   ExceptionsCount Average Min Percentile2 LowerQuartile   Median  UpperQuartile   Percentile98    Max

**Comment by fandrei** [comment]
PS added exceptions count too
