### ISSUE TITLE
Problem with metrics.labs.cityindex.com load balancer

### ISSUE THREAD

**Issue by fandrei** [fandrei/AppMetrics#33]
Load balancer for split testing works ok now, it redirects all requests to either current.metrics.labs.cityindex.com or next.metrics.labs.cityindex.com
However, redirected requests lose original client IP information and show server's IP for all requests instead.

**Comment by fandrei** [comment]
It seems this happens when redirection goes from one website to another (i.e. from current.metrics.labs.cityindex.com to the real logger web site). I guess because technically it really makes requests from one site from another. It seems there is no way to avoid this problem, if we use site redirection for load balancing.

PS probably we should just install sites to current/next locations, rather then use redirection

**Comment by fandrei** [comment]
UPD the same problem with load balancer itself; when I install logger directly to next.metrics.labs.cityindex.com then IP logging works ok. But when I use metrics.labs.cityindex.com address, IP is replaced with server's IP

**Comment by mrdavidlaing** [comment]
Have decided not to fix; but rather to remove the use of a load balancer in the architecture.
