### ISSUE TITLE
Export raw data to Amazon S3

### ISSUE THREAD

**Issue by mrdavidlaing** [fandrei/AppMetrics#34]
I'd like to backup the raw data logs to Amazon S3; since this provides both redundant backup & a good integration point for getting data into Elastic Map Reduce.

**Comment by fandrei** [comment]
Should it copy data to Amazon S3 when session is finished, or when every new piece of data arrives?

**Comment by fandrei** [comment]
Do we have an account on Amazon for debugging?

**Comment by mrdavidlaing** [comment]
I can set one up for you.  What access to you need?

On Thursday, March 22, 2012, fandrei <
reply@reply.github.com>
wrote:

> Do we have an account on Amazon for debugging?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/fandrei/AppMetrics/issues/34#issuecomment-4633889

## 

David Laing
Open source @ City Index - github.com/cityindex
http://davidlaing.com
Twitter: @davidlaing

**Comment by fandrei** [comment]
I guess Amazon AWS account with S3 enabled is enough.

**Comment by mrdavidlaing** [comment]
I'll get to it tomorrow.

On Thursday, March 22, 2012, fandrei <
reply@reply.github.com>
wrote:

> I guess Amazon AWS account with S3 enabled is enough.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/fandrei/AppMetrics/issues/34#issuecomment-4634665

## 

David Laing
Open source @ City Index - github.com/cityindex
http://davidlaing.com
Twitter: @davidlaing
