### ISSUE TITLE
Evaluate having Chinese based ODeskers run CIAPILatencyCollector

### ISSUE THREAD

**Issue by mrdavidlaing** [fandrei/AppMetrics#39]
(1) Find out how many Chinese ODeskers would / could run the CIAPILatencyCollector
(2) Find out how much it would cost us on a monthly basis

**Comment by fandrei** [comment]
I think we should decide about API key before starting this.
As far as I understand, it should be secret, i.e. we can’t include it into public source code?

**Comment by mrdavidlaing** [comment]
At the end of the day its never going to be possible to totally secure the
AppKey from a determined hacker, so lets just pick one, and compile it in
during the build process.

If someone decompiles the app & grabs it, or watches the API traffic to get
it, then so be it.  I'm monitoring for API call patterns that don't match
the norm for a specific AppKey, at which stage we'll issue a new app key
and ban the old one.

At this stage, just pick some random string as the app key, and drop me an
email with it so I can make sure it doesn't get blocked.

On 23 March 2012 11:21, fandrei <
reply@reply.github.com

> wrote:
> 
> I think we should decide about API key before starting this.
> As far as I understand, it should be secret, i.e. we can’t include it into
> public source code?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/fandrei/AppMetrics/issues/39#issuecomment-4657334

## 

David Laing
Open source @ City Index - github.com/cityindex
http://davidlaing.com
Twitter: @davidlaing

**Comment by fandrei** [comment]
Ok, API key is embedded
https://github.com/fandrei/AppMetrics/issues/51

**Comment by fandrei** [comment]
For the beginning and as a less-hassle variant, we can use Windows Azure - they have application hosting in Hong Kong.

**Comment by mrdavidlaing** [comment]
Azure is going to suffer from the same issues as Amazon EC2 - we'll be using machines with datacenter grade internet connectivity.

What we want is data from office or home grade connections.

**Comment by mrdavidlaing** [comment]
Recruiting via ODesk hasn't worked, so lets bin that idea.

I've started emailing other City Index contacts asking them to run the CIAPILatencyCollector agent on their machines in the remote City Index offices.
