### ISSUE TITLE
CIAPILatencyCollector service GUI

### ISSUE THREAD

**Issue by mrdavidlaing** [fandrei/AppMetrics#40]
Need a GUI to edit the CIAPILatencyCollector settings, and see what it is currently doing / reporting.

A historic view of events (a log) would be very useful

**Comment by mrdavidlaing** [comment]
A usecase - the CIAPILatencyCollector on my CityIndex work PC keeps dying.

I need a way to debug why - currently the only way I notice is that the reports for the UK - http://analytics.metrics.labs.cityindex.com/GetReport.ashx?Application=CIAPILatencyCollector&Locations=United%20Kingdom&Period=0:1:0 seems to have a lot of gaps, until I restart the CIAPI Latency Collector service

**Comment by fandrei** [comment]
It already has event log - you can see it in the system Event Viewer (Windows Logs/Application). Exceptions in the system service should be reported there. 
GUI settings are available too - see "C:\ProgramData\City Index\CIAPI Latency Collector\bin\CiapiLatencyCollectorConfig.exe"

**Comment by mrdavidlaing** [comment]
Ok; lets expand these tools when we discover exactly what additional debugging data is required
