### ISSUE TITLE
Compress finished sessions data

### ISSUE THREAD

**Issue by fandrei** [fandrei/AppMetrics#41]

**Comment by mrdavidlaing** [comment]
What is the reason for this?

If it is to save space then we should rather consider just archiving to s3

On Tuesday, March 20, 2012, fandrei <
reply@reply.github.com>
wrote:

> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/fandrei/AppMetrics/issues/41

## 

David Laing
Open source @ City Index - github.com/cityindex
http://davidlaing.com
Twitter: @davidlaing

**Comment by fandrei** [comment]
Yes, idea was to save space. But if we archive old sessions to S3, it's better to compress them anyway, to save money :)

**Comment by mrdavidlaing** [comment]
You are right.  So compress away!

On Wednesday, March 21, 2012, fandrei <
reply@reply.github.com>
wrote:

> Yes, idea was to save space. But if we archive old sessions to S3, it's
> better to compress them anyway, to save money :)
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/fandrei/AppMetrics/issues/41#issuecomment-4612026

## 

David Laing
Open source @ City Index - github.com/cityindex
http://davidlaing.com
Twitter: @davidlaing
