### ISSUE TITLE
Deploy via mono on Linux nodes in all AWS datacenters

### ISSUE THREAD

**Issue by mrdavidlaing** [fandrei/AppMetrics#44]
The clocks on Windows EC2 nodes are suspect, whereas the clocks on Linux (Ubuntu 11.10) nodes are much more accurate.

We need a version of the CIAPILatencyCollector that runs under Mono, as a service on Ubuntu 11.10

**Comment by fandrei** [comment]
It's not that simple, as system service (and possibly auto-update) code won't work on Linux.
As alternative, we can call NTP protocol directly to get precise time in our program.

**Comment by mrdavidlaing** [comment]
As long as we're running an NTP service on the windows EC2 machine (eg: http://www.meinberg.de/english/sw/ntp.htm#ntp_nt_stable) then the clock accuracy seems to be within 5ms.  This is good enough for our measurements, so we don't need Linux nodes
