### ISSUE TITLE
Add streaming latency & jitter collectors to CIAPILatencyCollector

### ISSUE THREAD

**Issue by mrdavidlaing** [fandrei/AppMetrics#45]
To feed data into the relevant reports.

**Comment by fandrei** [comment]
What market prices it needs to stream?

**Comment by mrdavidlaing** [comment]
Lets start with

```
400481142   GBP/USD
```

For account XX870869

We'll add the metronome price as soon as I get the HeartbeatPriceService delivered (looking like it will take 6 weeks)
