### ISSUE TITLE
Create latency collector "spec" & reference implementation

### ISSUE THREAD

**Issue by mrdavidlaing** [fandrei/AppMetrics#46]
The FlexITP & Mobile teams have agreed to also provide latency measurement data for us from the actual applications clients are using.

We need to give them a simple latency collector "spec" and C# reference implementation that shows exactly how to calculate the data, and post it back to metrics.labs.cityindex.com

**Comment by fandrei** [comment]
Created a sample:
https://github.com/fandrei/AppMetrics/tree/master/samples/ReportingToAppMetrics
