### ISSUE TITLE
Evaluate possibility of direct usage of NTP to get precise time

### ISSUE THREAD

**Issue by fandrei** [fandrei/AppMetrics#54]

**Comment by fandrei** [comment]
Ok, it seems we can achieve precision ~0.1 seconds if using SNTP to request servers from pool.ntp.org directly. Probably it's possible to make it more precise by using full NTP algorithms.
(for comparison, on my PC windows time sync has error at least +-1 second according to my experiments)

**Comment by fandrei** [comment]
As alternative, we can bundle windows port of ntpd into latency collector application; this way we should be able to achieve clock accuracy of ~0.01 seconds

**Comment by mrdavidlaing** [comment]
We should just install a windows NTP service like http://www.meinberg.de/english/sw/ntp.htm#ntp_nt_stable on those machines whoes clocks we don't trust.

We probably can't bundle it with the CIAPILatencyCollector installer, because some of our collection nodes (those on the CityIndex domain for example), cannot use a non domain time source.

It would be useful for the CIAPILatencyCollector to be able to detect the error estimate of a machines clock, and include that data in the logs send to AppMetrics.

**Comment by fandrei** [comment]
I think we shouldn't trust windows time service at all.
It's possible to embed ntpd into the latency collector and use it's time internally only, so it won't affect machine clock.

**Comment by fandrei** [comment]
It seems we have the following options here:
1. Just install windows port of ntpd on every client node (what requires lots of additional manual steps for installation)
2. Embed ntpdate tool into the latency collector program and use it to periodically query time offset value (without setting system clock)
3. Embed ntpd and run it to make time adjustments continuously, what gives us more precise time; however, it always tries to set system clock. It’s impossible to make it  only report time adjustment value. (Setting system clock requires elevated privileges, what is not appropriate for the latency collector service). However, I think it’s possible to build customized version of ntpd, that will only report us precise time instead of setting system clock.

**Comment by mrdavidlaing** [comment]
I'm for 1.  We can automate server setup

**Comment by fandrei** [comment]
Some additional observations:

ntpdate (option 2) doesn't work very well, it gives spread at least +-0.2 seconds when running several times

some machines have port 123 blocked by firewall and can't use NTP protocol

windows time service (w32time) gives big error, at least +-0.8 seconds even when connected to a domain time source

I've made a custom time sync code on base of improved SNTP protocol (now testing it in the experimental price streaming latency tracker), it gives error +-0.02 seconds approximately

**Comment by fandrei** [comment]
PS we can try to use internal NTP time source to deal with blocked NTP ports

**Comment by fandrei** [comment]
PPS as alternative, I've made experiments with time synchronization over HTTP and it seems it's possible to achieve precision ~0.05 seconds this way, when syncing my PC with AppMetrics server in US

**Comment by mrdavidlaing** [comment]
Given the following design goals:

(1) We only want to process price latency measurements where we can be sure of clock precision that is better than 10ms (0.01s)
(2) CIAPILatencyCollector should NOT set the system clock
(3) CIAPILatencyCollector should report the current systems clock error when reporting latency numbers, so we can discard metrics where the error level is too high

It looks like the only why to get the precision we need is by having the node run ntpd (http://www.meinberg.de/english/sw/ntp.htm#ntp_nt_stable).  For the moment, lets install that manually on all the Amazon EC2 collector nodes.

To satisfy (3), we need to query, in order:

(a) The ntpd loopstats files, archived at C:\Program Files\NTP\etc (see https://github.com/fandrei/AppMetrics/issues/58#issuecomment-5095054)
(b) w32tm

**Comment by fandrei** [comment]
It seems w32time log is completely useless due to it's inaccuracy.
I added code to check ntpd stats, it works in this way: read loopstats files of last 2 days and report last, min (negative) and max offsets to the server. 
When building reports the server checks, if abs value of offset was bigger than 0.01 seconds. If all offsets are smaller, then time is stable enough and we can use streaming latency data from this source.

It seems, at this moment time of the most of servers is not accurate enough.

PS when auto-creating new instances using Chef, it's necessary to turn off windows time sync. It only spoils everything.

**Comment by mrdavidlaing** [comment]
The installation of Mienberg NTPd disables W32Tm (specifically the Windows
Time Service)

Is that what you mean?

On 3 May 2012 10:46, fandrei <
reply@reply.github.com

> wrote:
> 
> It seems w32time log is completely useless due to it's inaccuracy.
> I added code to check ntpd stats, it works in this way: read loopstats
> files of last 2 days and report last, min (negative) and max offsets to the
> server.
> When building reports the server checks, if abs value of offset was bigger
> than 0.01 seconds. If all offsets are smaller, then time is stable enough
> and we can use streaming latency data from this source.
> 
> It seems, at this moment time of the most of servers is not accurate
> enough.
> 
> PS when auto-creating new instances using Chef, it's necessary to turn off
> windows time sync. It only spoils everything.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/fandrei/AppMetrics/issues/54#issuecomment-5484212

## 

David Laing
Open source @ City Index - github.com/cityindex
http://davidlaing.com
Twitter: @davidlaing

**Comment by fandrei** [comment]
It seems it doesn't, because the most of our amazon instances had windows time sync on (I turned it off manually)
