### ISSUE TITLE
Generate report on estimated accuracy of node clocks

### ISSUE THREAD

**Issue by mrdavidlaing** [fandrei/AppMetrics#58]
Figure out how to measure the accuracy; probably through the use of a third party program

At a later stage we can focus on improving this accuracy.

**Comment by mrdavidlaing** [comment]
Meinberg's NTP service & monitor tools - http://www.meinberg.de/english/sw/ntp.htm - look quite comprehensive

**Comment by mrdavidlaing** [comment]
Here is another tool that is useful for visualising the NTP stats - loopstats & peerstats - http://satsignal.eu/software/net.htm#NTPplotter

**Comment by mrdavidlaing** [comment]
Seems that Amazon run some NTP servers - 

```
server 0.amazon.pool.ntp.org
server 1.amazon.pool.ntp.org
server 2.amazon.pool.ntp.org
server 3.amazon.pool.ntp.org
```

No idea where these are located, or if they resolve to different machines depending on datacenter

**Comment by fandrei** [comment]
pool.ntp.org resolves to the nearest NTP server, and it seems it includes these servers too. 
What about idea to include windows port of ntpd into the latency collector?

**Comment by mrdavidlaing** [comment]
If that is possible, then I think including windows port of ntpd in latency collector is excellent idea

**Comment by mrdavidlaing** [comment]
Looks like after a few days of running windows port of NTPd, a m1.small Windows 2008 machine in US-East can have time accuracy of +- 5ms, which is good enough for our measurement purposes.

<img src="http://dl.dropbox.com/u/33609233/CIAPI/NTP-plotter-AmazonEC2%20machine%20-%2012%20Apr%202012%2017.30.09.png"/>

**Comment by mrdavidlaing** [comment]
As a comparison, here is a graph of the ntpd stats for labs.cityindex.com, an Ubuntu 11.10 machine running on a t1.micro instance in EU-West.  This seems to have an accuracy of +- 1 ms

<img src="http://dl.dropbox.com/u/33609233/CIAPI/NTPplotter%20-%20AmazonEC2%20linux%20machine%20-%20%2012%20Apr%202012%2018.03.41.png"/>

**Comment by mrdavidlaing** [comment]
As long as we're running an NTP service on the windows EC2 machine (eg: http://www.meinberg.de/english/sw/ntp.htm#ntp_nt_stable) then the clock accuracy seems to be within 5ms.  This is good enough for our measurements.
