### ISSUE TITLE
Split Solarwinds USA region

### ISSUE THREAD

**Issue by mrdavidlaing** [fandrei/AppMetrics#65]
Currently the solarwinds reports aggregate all US traffic into one; but looking at the traffic distribution on the marketing websites, we should be reporting this by datacenter region (i.e, so we can compare US west coast to US east coast)

<img src="http://dl.dropbox.com/u/33609233/AppMetrics/distribution_of_US_traffic.png"/>

**Comment by fandrei** [comment]
To achieve this, I need to add capability to split reports by location more precisely (i.e. by country, region and city). Unfortunately GeoIP has invalid location data for our american servers, thus overriding data is required. 
In other words this is a new feature rather than refactoring.

**Comment by fandrei** [comment]
I've added extended capabilities for report slicing:

http://analytics.metrics.labs.cityindex.com/GetReport.ashx?Application=CiapiLatencyCollector&Type=LatencySummaries&SliceByLocation=CountriesAndCities
(report sliced by precise location)

http://analytics.metrics.labs.cityindex.com/GetReport.ashx?Application=CiapiLatencyCollector&Type=LatencySummaries&Type=LatencySummaries&SliceByLocation=CountriesAndCities&Locations=United%20States
(United States only)

http://analytics.metrics.labs.cityindex.com/GetReport.ashx?Application=CiapiLatencyCollector&Type=LatencySummaries&Type=LatencySummaries&SliceByLocation=CountriesAndCities&Locations=United%20States%2fArizona
(Arizona only)
