### ISSUE TITLE
Silent installer

### ISSUE THREAD

**Issue by mrdavidlaing** [fandrei/AppMetrics#66]
The chef automation recipes need to install the CIAPI Latency Collector service from the command line.

See [cookbooks/windows_ciapilatencycollector/recipes/default.rb#L24](https://github.com/cityindex/cookbooks/blob/91bd43bdc2fa8bc4a5a144e87b1c63f2ed80325b/cookbooks/windows_ciapilatencycollector/recipes/default.rb#L24)

we either need to be able to:
- pass the required options on the command line or 
- to be able to disable the modal dialog, and have chef create the config file from a template.

**Comment by fandrei** [comment]
Is it possible for Chef to run installed exe after installation?

**Comment by fandrei** [comment]
Syntax for quiet installation: 

msiexec /i CiapiLatencyCollector.msi /quiet
"C:\Program Files (x86)\City Index\CIAPI Latency Collector\CiapiLatencyCollectorConfig.exe"  -username:SomeUserName -password:SomePassword

**Comment by mrdavidlaing** [comment]
Running 

```
"C:\Program Files (x86)\City Index\CIAPI Latency Collector\CiapiLatencyCollectorConfig.exe" -username:SomeUserName -password:SomePassword
```

still pops up a modal dialog, which kills the chef run.

Please can you amend this so that it can be run without any user intervention (ie, without a modal dialog poping up)

**Comment by fandrei** [comment]
it shouldn't popup dialog, plz check that you are using the latest version

**Comment by mrdavidlaing** [comment]
All good since v1.0.70.

On 3 May 2012 12:56, fandrei <
reply@reply.github.com

> wrote:
> 
> it shouldn't popup dialog, plz check that you are using the latest version
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/fandrei/AppMetrics/issues/66#issuecomment-5485928

## 

David Laing
Open source @ City Index - github.com/cityindex
http://davidlaing.com
Twitter: @davidlaing
