### ISSUE TITLE
Implement AllServiceMonitor

### ISSUE THREAD

**Issue by mrdavidlaing** [fandrei/AppMetrics#73]
Should make a call to each of the major service urls:
1. Login
2. Client details
3. List markets
4. List news
5. Get market info
6. Get price history for single market
7. Place Buy trade on market
8. List open positions
9. List account summary
10. Close Buy trade on market
11. Logout

**Comment by fandrei** [comment]
what about price streaming?

**Comment by mrdavidlaing** [comment]
Let's implement this first and then decide once we know which parts of the
idea work.

  However, I was thinking that it would just become an additional monitor,
where the period is the time after which it disconnects and reconnects.

On Thursday, May 17, 2012, fandrei wrote:

> what about price streaming?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/fandrei/AppMetrics/issues/73#issuecomment-5759563

## 

David Laing
Open source @ City Index - github.com/cityindex
http://davidlaing.com
Twitter: @davidlaing

**Comment by fandrei** [comment]
What you mean as "List account summary"?

**Comment by mrdavidlaing** [comment]
https://ciapipreprod.cityindextest9.co.uk/ciapi.docs/#service.ListTradeHistoryis
the closest I guess

On 18 May 2012 11:27, fandrei <
reply@reply.github.com

> wrote:
> 
> What you mean as "List account summary"?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/fandrei/AppMetrics/issues/73#issuecomment-5783246

## 

David Laing
Open source @ City Index - github.com/cityindex
http://davidlaing.com
Twitter: @davidlaing

**Comment by mrdavidlaing** [comment]
We need to disable the trade calls (7 & 10) for now - need to run some internal testing to ensure there are no unexpected problems with downstream reports before "going live"

**Comment by fandrei** [comment]
ok, I'll make option for this.
Anyway, I need to finish monitor configs first

**Comment by fandrei** [comment]
added an AllowTrading option
