### ISSUE TITLE
Update Solarwinds reports

### ISSUE THREAD

**Issue by mrdavidlaing** [fandrei/AppMetrics#75]
One set of reports comparing latency across nodes

Another comparing latency across services

**Comment by mrdavidlaing** [comment]
working on it...

**Comment by fandrei** [comment]
I updated scripts here https://github.com/fandrei/AppMetrics/tree/master/Solarwinds

**Comment by mrdavidlaing** [comment]
I've got some simplified & updated scripts running in PPE.  Will leave them running for a week before starting the process of migrating to live.

Still need to figure out how to make the baseUrl (http://analytics.metrics.labs.cityindex.com vs http://analytics.metrics.cityindex.com) a config option (like Username/Password) rather than hardcoded into the script

**Comment by mrdavidlaing** [comment]
Bummer - looks like v5 of Solarwinds SAM doesn't support script variables - although it is slated for the next release.

http://thwack.solarwinds.com/thread/47254

**Comment by mrdavidlaing** [comment]
Have a [temporary workaround based on monitoring node IP](https://github.com/fandrei/AppMetrics/blob/c2cf39b81c05d997a54e0c9e7f4e97414c9f02f3/Solarwinds/CIAPI%20Latency%20Monitor.apm-template#L98-101)

```
$baseUrl = "http://analytics.metrics.cityindex.com"
if ("${IP}" -eq "192.168.169.104") {
   $baseUrl = "http://analytics.metrics.labs.cityindex.com"
}

$url = $baseUrl + $query.Replace("`"", "")
```

This will have to do until Solarwinds supports script variables
