### ISSUE TITLE
Service using 100% CPU

### ISSUE THREAD

**Issue by mrdavidlaing** [fandrei/AppMetrics#77]
The ap-northeast-1, us-east-1b & us-west-1b nodes have been using 100% CPU for at least the last day.  I've RDPed to all & killed the service (stopping didn't work).  I've restarted just ap-northeast-1

This screencast shows perfmon data for ap-northeast-1: https://cityindex.viewscreencasts.com/7142d81cd0e540a798f3b7888316b31c 

Node specifics are

```
region: ap-northeast-1
public_hostname:        ec2-54-248-116-221.ap-northeast-1.compute.amazonaws.com
public_ipv4:                  54.248.116.221
id:   AMAZONA-67GGBTA

region: us-west-1b
public_hostname:              ec2-184-169-142-250.us-west-1.compute.amazonaws.com
public_ipv4:                  184.169.142.250
id:   AMAZONA-G463OLI

region: us-east-1b
public_hostname:              ec2-23-21-131-181.compute-1.amazonaws.com
public_ipv4:                  23.21.131.181             
id:   AMAZONA-SCIFQUA
```

**Comment by mrdavidlaing** [comment]
Any ideas?  Doesn't seem to have happened again over the last week

**Comment by fandrei** [comment]
I've made some refactoring in multi-threading code, hopefully it will address this problem. And I've added code to report CPU usage of the current process periodically for better diagnostics.

**Comment by mrdavidlaing** [comment]
The splunk monitoring already collects all the CPU stats, remind me to show
you how to get them.

On Thursday, June 7, 2012, fandrei wrote:

> I've made some refactoring in multi-threading code, hopefully it will
> address this problem. And I've added code to report CPU usage of the
> current process periodically for better diagnostics.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/fandrei/AppMetrics/issues/77#issuecomment-6168497

## 

David Laing
Open source @ City Index - github.com/cityindex
http://davidlaing.com
Twitter: @davidlaing

**Comment by fandrei** [comment]
splunk shows only total CPU usage rather than per-process, or I'm wrong?

**Comment by mrdavidlaing** [comment]
Nope - that is correct.  However, it is straight forward to log the output
of any windows command into splunk, eg:

Create a powershell script to grab the CPU metrics -
http://splunk-base.splunk.com/answers/5431/identify-which-process-is-chewing-up-cpu-on-windows

And call said script from the forwarder -
http://splunk-base.splunk.com/answers/309/powershell-scripted-input

On the metrics machine `$SPLUNK_HOME is` `c:\program
files\splunkuniversalforwarder`

On 7 June 2012 09:27, fandrei <
reply@reply.github.com

> wrote:
> 
> splunk shows only total CPU usage rather than per-process, or I'm wrong?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/fandrei/AppMetrics/issues/77#issuecomment-6170973

## 

David Laing
Open source @ City Index - github.com/cityindex
http://davidlaing.com
Twitter: @davidlaing

**Comment by mrdavidlaing** [comment]
CPU usage has dropped in last 2 weeks.
