### ISSUE TITLE
Create centralized config system

### ISSUE THREAD

**Issue by fandrei** [fandrei/AppMetrics#79]
One of the config options should be a remote config, where the configuration is retrieved via an HTTP call to a central server.

It should be possible to change the config of all the running nodes by editing a set of files on a central server.

**Comment by mrdavidlaing** [comment]
Here is a potential design idea:

On the config server, have a HTTP directory structure (protected by HTTP auth) as follows:

```
http://{config.server}/CIAPILatencyCollectorConfig/{node1}/AppSettings.xml
                                                   {node2}/AppSettings.xml
                                                   {node3}/AppSettings.xml
```

where [AppSettings is in the format described](https://github.com/fandrei/AppMetrics/issues/71#issuecomment-5961909) in #71

The local AppSettings.xml for each node then becomes:

```
<RemoteConfig xsi:type="HttpRemoteConfig">
    <Uri>http://{configserver}/CIAPILatencyCollectorConfig/{node1}/AppSettings.xml</Uri>
    <UserName>{config_username}</UserName>
    <EncryptedPassword>{config_password}</EncryptedPassword>
    <PeriodSeconds>60</PeriodSeconds>
</RemoteConfig>
```

In this scenario the config is refreshed every 60 seconds from the specified Uri.  There is no need for the downloaded config to be persisted locally.

This is an extension to the local config - it should remain possible to just store all the config locally as it is currently.

Does this sound workable?

**Comment by fandrei** [comment]
Sounds not too complicated.
What type of authentication better to use?

**Comment by mrdavidlaing** [comment]
Let go for the simplest option - perhaps something built into IIS like
Basic Auth?

On 4 June 2012 09:24, fandrei <
reply@reply.github.com

> wrote:
> 
> Sounds not too complicated.
> What type of authentication better to use?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/fandrei/AppMetrics/issues/79#issuecomment-6094400

## 

David Laing
Open source @ City Index - github.com/cityindex
http://davidlaing.com
Twitter: @davidlaing

**Comment by fandrei** [comment]
Built-in basic authentication requires credentials to match built-in windows credentials
http://msdn.microsoft.com/en-us/data/gg192997.aspx
(some additional info)
http://www.iis.net/ConfigReference/system.webServer/security/authentication/basicAuthentication
http://technet.microsoft.com/en-us/library/cc772009(v=WS.10).aspx

otherwise, it's necessary to implement custom authentication module (I can reuse one created for AppMetrics site)

**Comment by mrdavidlaing** [comment]
Lets use the AppMetrics one

**Comment by fandrei** [comment]
ok, almost done. Need to finish some bugfixing and refactoring.

**Comment by fandrei** [comment]
One possible issue here is about using IP address to distinguish nodes, because some nodes can have dynamic IP.
You don't mind if I use unique user ID instead? Or something else?

**Comment by mrdavidlaing** [comment]
Rather than userid, use a string node name that we can assign on install of
the node.

On Thursday, June 7, 2012, fandrei wrote:

> One possible issue here is about using IP address, because some nodes can
> have dynamic IP.
> You don't mind if I use unique user ID instead?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/fandrei/AppMetrics/issues/79#issuecomment-6168601

## 

David Laing
Open source @ City Index - github.com/cityindex
http://davidlaing.com
Twitter: @davidlaing

**Comment by fandrei** [comment]
You mean "AMAZONA-9TCJ5QA", etc?

**Comment by mrdavidlaing** [comment]
No,  something you set on service install that is more friendly like
"Tokyo" or "steffen's Germany machine"

On Thursday, June 7, 2012, fandrei wrote:

> You mean "AMAZONA-9TCJ5QA", etc?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/fandrei/AppMetrics/issues/79#issuecomment-6170920

## 

David Laing
Open source @ City Index - github.com/cityindex
http://davidlaing.com
Twitter: @davidlaing

**Comment by fandrei** [comment]
ok, easy

**Comment by fandrei** [comment]
done... to make it working, it's necessary to update latency collectors config - set credentials for access to configs repository and node friendly name:
"C:\Documents and Settings\All Users\Application Data\City Index\CIAPI Latency Collector\bin\CiapiLatencyCollectorConfig.exe" -username:SomeUser -password:SomePassword -nodename:SomeHost

**Comment by fandrei** [comment]
([08.06.2012 19:50:07] David Laing)

and make reporting url configuration option in monitor config
eg:

```
<LatencyMonitor xsi:type="DefaultPageMonitor">
  <LogEventUrl>http://metrics.labs.cityindex.com/LogEvent.ashx</LogEventUrl>
  <PeriodSeconds>6</PeriodSeconds>
</LatencyMonitor>
```

**Comment by fandrei** [comment]
How I should deal with exceptions in the monitor controlling framework? Make option where report these data as well?

**Comment by mrdavidlaing** [comment]
I'd say write these to a local log file (in case the exception is to do with .net access)

Splunk can automatically local log files just like it does for the NTP loopstats log files

**Comment by mrdavidlaing** [comment]
After discussion, we decided to log exceptions in the monitor controlling framework back to the AppMetrics server
