### ISSUE TITLE
Include CIAPILatencyCollector.msi inside the central config website.

### ISSUE THREAD

**Issue by mrdavidlaing** [fandrei/AppMetrics#89]
When you install the config website, you should also be installing a copy of the CIAPILatencyCollector.msi that is accessable via http://config.metrics.{your_tld}/Installs/CIAPILatencyCollector.msi

When you configure a collector node, you grab the msi from this location.

If you want to update the services on all the nodes, you just update the msi in the config site.

**Comment by fandrei** [comment]
One adjustment: update package is a zip file, not msi

Should we make a Jenkins task to auto-deploy update package for the preprod monitoring system?

**Comment by mrdavidlaing** [comment]
Yes - we want to keep the Jenkins autodeploy for the metrics.labs.cityindex.com environment.

But, we want the production environment deploy to be done manually, but updating the zip in the config site

**Comment by fandrei** [comment]
update package is stored to the folder _UpdatePackage under solution root, 
and automatically deployed to http://config.metrics.labs.cityindex.com/CIAPILatencyCollector/updates/
