### ISSUE TITLE
Setup metrics.labs.cityindex.com loadbalancer

### ISSUE THREAD

**Issue by mrdavidlaing** [fandrei/AppMetrics#9]
Setup a "load balancer" behind metrics.labs.cityindex.com; that sends 90% of the traffic to the "current" deployment, and 10% to the "release candidate" deployment.

**Comment by mrdavidlaing** [comment]
IIS7 should be able to do this for us:  http://learn.iis.net/page.aspx/486/http-load-balancing-using-application-request-routing/

**Comment by mrdavidlaing** [comment]
metrics.labs.cityindex.com domain is now setup
*.metrics.labs.cityindex.com -> metrics.labs.cityindex.com

```
 Pinging metrics.labs.cityindex.com [184.73.228.71] with 32 bytes of data:
 Pinging metrics.labs.cityindex.com [184.73.228.71] with 32 bytes of data:
```

IIS ARR load balancing is setup to round robin between current & next

**Comment by mrdavidlaing** [comment]
Currently only one of these 2 is requesting authentication

**Comment by fandrei** [comment]
It should work correctly now
