### ISSUE TITLE
Rework Backup task

### ISSUE THREAD

**Issue by mrdavidlaing** [fandrei/AppMetrics#90]
- Make [NonArchivePeriod](https://github.com/fandrei/AppMetrics/blob/master/Backup/BackupHandler.cs#L183) a config option
- Is S3 the right place?
- What period of data do we need accessible?

**Comment by mrdavidlaing** [comment]
Another alternative is to just rely on the nightly AMI creation backup job for the whole server.  Moving stuff to S3 doesn't have any advantage in terms of data safety (AMIs are stored on S3 anyway); and getting at the data on S3 is more of a hassle

**Comment by fandrei** [comment]
Works for me. Then, we remove S3 backup?

**Comment by mrdavidlaing** [comment]
Agreed.  Remove S3 backup.  Easiest code to maintain is code you have deleted :)

**Comment by fandrei** [comment]
What about zipping of old log files; should I keep scheduler task for this, or make it built into AppMetrics website?

**Comment by mrdavidlaing** [comment]
I'd say keep it as a separate command line tool that can be called via the scheduler.

My experience of trying to get long running tasks working in the context of IIS just a hassle.
