### ISSUE TITLE
Refactoring of the CiapiLatencyCollector

### ISSUE THREAD

**Issue by fandrei** [fandrei/AppMetrics#91]
1. Split the latency collector into parts - general purpose framework code, and CIAPI latency monitor
2. General purpose code is named AppMetricsAgent and moves to AppMetrics project
3. Add capability to deploy CIAPI latency monitor as a separate assembly in the subfolder of Agent's working directory

**Comment by mrdavidlaing** [comment]
Based on this, I'd like eventually remove fandrei/CIAPILatencyCollector, and just have a private cityindex/CIAPILatencyCollector repo that uses the monitor framework and has a bunch of private monitors (Miranda, GTS etc)
