### ISSUE TITLE
AllServiceMonitor - don't fail completely if single service fails

### ISSUE THREAD

**Issue by mrdavidlaing** [fandrei/AppMetrics#93]
During the PPE test today the Price history service was down.  

This caused monitor of half of the other services not to be attempted. (because they are all [within the same try catch block](https://github.com/fandrei/CiapiLatencyCollector/blob/master/LatencyCollectorCore/Monitors/AllServiceMonitor.cs#L55) )

In the case of a single service failing, as the other services should still be attempted (where possible)

**Comment by fandrei** [comment]
done. should I push it to master now?

**Comment by mrdavidlaing** [comment]
yes

On 11 July 2012 08:05, Andrei Faber <
reply@reply.github.com

> wrote:
> 
> done. should I push it to master?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/fandrei/AppMetrics/issues/93#issuecomment-6899621

## 

David Laing
Open source @ City Index - github.com/cityindex
http://davidlaing.com
Twitter: @davidlaing

**Comment by fandrei** [comment]
done
