### ISSUE TITLE
Make appmetrics server that CIAPILatencyCollector logs data to configurable

### ISSUE THREAD

**Issue by mrdavidlaing** [fandrei/AppMetrics#98]
Currently the [appmetrics server that data is logged to is hardcoded](https://github.com/fandrei/CiapiLatencyCollector/blob/master/LatencyCollectorCore/Program.cs#L33)

This needs to be a config option

**Comment by fandrei** [comment]
This is used only when getting remote settings fails for some reason; actual initialization of tracking location is here https://github.com/fandrei/CiapiLatencyCollector/blob/master/LatencyCollectorCore/Program.cs#L114
